application:
  banking:
    bank-code: 214241
spring:
  datasource:
    url: jdbc:h2:file:./data/banking;AUTO_SERVER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
springdoc:
  api:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html