CREATE TABLE TRANSACTIONS (
    ID BINARY(16) PRIMARY KEY,
    SOURCE_IBAN VARCHAR(34) NOT NULL,
    TARGET_IBAN VARCHAR(34),
    AMOUNT DECIMAL(19,2) NOT NULL,
    CURRENCY VARCHAR(16) NOT NULL,
    USER_ID BIGINT NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    TRANSACTION_DATE TIMESTAMP NOT NULL,
    SOURCE_ACCOUNT_ID BINARY(16) NOT NULL,
    TARGET_ACCOUNT_ID BINARY(16),

    CONSTRAINT fk_transactions_user
        FOREIGN KEY (USER_ID) REFERENCES USERS(id),
    CONSTRAINT fk_transactions_target_account
        FOREIGN KEY (TARGET_ACCOUNT_ID) REFERENCES ACCOUNTS(id),
    CONSTRAINT fk_transactions_source_account
        FOREIGN KEY (SOURCE_ACCOUNT_ID) REFERENCES ACCOUNTS(id)
);