CREATE TABLE ACCOUNTS (
    ID BINARY(16) PRIMARY KEY,
    IBAN VARCHAR(34) NOT NULL UNIQUE,
    ACCOUNT_NAME VARCHAR(255) NOT NULL,
    BALANCE DECIMAL(19,2) NOT NULL DEFAULT 0.00,
    USER_ID BIGINT NOT NULL,
    CONSTRAINT fk_accounts_user FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);